server:
  port: 8080
spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/lovematch
    username: lovematch
    password: lovematch
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
api:
  culture:
    key: 9f2fa7ad-c4b1-47ea-873d-81094462a602
  #    ???????_?? ?? ?? ?? ??(???) - ????
  kakao:
    key: ca08ac13070620b7b2281c0d40b29853
  #    ??? ??? ?? - ????
  culture2:
    key: 47594eb6-b4f5-4701-9400-e488524621da
  #    ?? ????? ?? ??????? ?_????(??) - ???
  culture3:
    key: 84a3cde9-fbbe-4764-b61f-d5527bc09b61
#    ??????? ?_?? ???? - ???
