server:
  port: 8090
spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/lovematch
    username: lovematch
    password: lovematch
    driver-class-name: com.mysql.cj.jdbc.Driver